import { useState, useEffect } from 'react';
import { initAgent, generatePlan, executePlan, fetchProviders, fetchExamples, fetchPrerun } from '../api/client';

function mdToHtml(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^(\d+)\.\s/gm, '<br>$1. ')
    .replace(/\n\n/g, '<br><br>')
    .replace(/\n/g, '<br>');
}

function buildMarkdown(query: string, plan: any, results: any): string {
  let md = `# LinkD Agent Analysis Report\n\n`;
  md += `## Query\n${query}\n\n`;
  if (plan?.steps) {
    md += `## Analysis Plan\n`;
    plan.steps.forEach((s: any) => {
      md += `${s.step_number}. ${s.description} *(${s.data_sources?.join(', ')})*\n`;
    });
    md += `\n`;
  }
  if (results?.steps) {
    md += `## Step Results\n`;
    results.steps.forEach((s: any) => {
      const icon = s.status === 'completed' ? '✅' : '❌';
      md += `### ${icon} Step ${s.step_number}: ${s.description}\n`;
      if (s.result_summary) md += `${s.result_summary}\n`;
      if (s.error) md += `**Error:** ${s.error}\n`;
      md += `\n`;
    });
  }
  if (results?.summary) {
    md += `## Analysis Summary\n${results.summary}\n`;
  }
  md += `\n---\n*Generated by LinkD Agent*\n`;
  return md;
}

function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadMarkdown(query: string, plan: any, results: any) {
  const md = buildMarkdown(query, plan, results);
  downloadFile(md, 'linkd_analysis.md', 'text/markdown');
}

function downloadPDF(query: string, plan: any, results: any) {
  // Generate a printable HTML and trigger browser print-to-PDF
  const md = buildMarkdown(query, plan, results);
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>LinkD Analysis Report</title>
<style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333;line-height:1.6}
h1{color:#2171B5;border-bottom:2px solid #2171B5;padding-bottom:8px}
h2{color:#2171B5;margin-top:24px}h3{margin-top:16px}
pre{background:#f5f5f5;padding:12px;border-radius:4px;white-space:pre-wrap}
hr{border:none;border-top:1px solid #e0e0e0;margin:24px 0}</style></head>
<body>${md.replace(/^# (.+)$/gm, '<h1>$1</h1>')
  .replace(/^## (.+)$/gm, '<h2>$1</h2>')
  .replace(/^### (.+)$/gm, '<h3>$1</h3>')
  .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  .replace(/\*(.+?)\*/g, '<em>$1</em>')
  .replace(/\n/g, '<br>')
  .replace(/---/g, '<hr>')}</body></html>`;
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}

const PRERUN_EXAMPLES = [
  { label: 'Vemurafenib-BRAF Analysis', name: 'vemurafenib_braf' },
  { label: 'EGFR Target Landscape', name: 'egfr_landscape' },
];

const QUERY_TYPES = [
  { type: 'Drug-target evidence', example: '"How strong is the evidence that vemurafenib binds to BRAF?"', icon: '🔬' },
  { type: 'Drug repurposing', example: '"Could erlotinib be repurposed for diseases beyond its current indications?"', icon: '💊' },
  { type: 'Target analysis', example: '"Which drugs most potently target EGFR, and how does EGFR rank?"', icon: '🎯' },
  { type: 'Disease exploration', example: '"What therapeutic options exist for melanoma through BRAF-targeted drugs?"', icon: '🏥' },
];

export default function Agent() {
  const [mode, setMode] = useState<'free' | 'custom'>('free');
  const [provider, setProvider] = useState('Google Gemini');
  const [model, setModel] = useState('gemini-2.5-flash');
  const [apiKey, setApiKey] = useState('');
  const [agentStatus, setAgentStatus] = useState('');
  const [query, setQuery] = useState('');
  const [plan, setPlan] = useState<any>(null);
  const [results, setResults] = useState<any>(null);
  const [prerunResult, setPrerunResult] = useState<any>(null);
  const [loading, setLoading] = useState('');
  const [providers, setProviders] = useState<any>({});
  const [examples, setExamples] = useState<any[]>([]);

  useEffect(() => {
    fetchProviders().then(setProviders);
    fetchExamples().then(d => setExamples(d.agent || []));
  }, []);

  const doInit = async () => {
    setLoading('init');
    const p = mode === 'free' ? 'Google Gemini' : provider;
    const m = mode === 'free' ? 'gemini-2.5-flash' : model;
    const k = mode === 'free' ? '' : apiKey; // empty key = server uses GEMINI_FREE_KEY
    const res = await initAgent({ provider: p, model: m, api_key: k });
    setAgentStatus(res.message || res.status);
    setLoading('');
  };

  const doPlan = async () => {
    setLoading('plan'); setResults(null); setPrerunResult(null);
    const res = await generatePlan(query);
    if (res.status === 'ok') setPlan(res);
    else setAgentStatus(res.message);
    setLoading('');
  };

  const doExecute = async () => {
    setLoading('execute');
    const res = await executePlan();
    if (res.status === 'ok') setResults(res);
    else setAgentStatus(res.message);
    setLoading('');
  };

  const loadPrerun = async (name: string) => {
    setLoading('prerun');
    const data = await fetchPrerun(name);
    setPrerunResult(data);
    setPlan(null); setResults(null);
    setLoading('');
  };

  const providerInfo = providers[provider];

  return (
    <div>
      <h2 className="text-xl font-bold text-gray-800 mb-2">LinkD-Agent: AI Analysis Agent</h2>

      {/* Instructions */}
      <div className="bg-blue-50 rounded-lg border border-blue-200 p-5 mb-6">
        <h3 className="text-sm font-bold text-[#2171B5] mb-2">What can LinkD-Agent do?</h3>
        <p className="text-xs text-gray-600 mb-3">
          The agent breaks complex biomedical questions into multi-step analysis plans, automatically querying
          binding affinity, EHR, drug response, and clinical trial data sources. It then synthesizes findings into a comprehensive summary.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {QUERY_TYPES.map((qt, i) => (
            <div key={i} className="bg-white rounded-lg p-3 border border-blue-100">
              <div className="text-lg mb-1">{qt.icon}</div>
              <div className="text-xs font-semibold text-gray-700 mb-1">{qt.type}</div>
              <div className="text-xs text-gray-400 italic">{qt.example}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Pre-run examples */}
      <div className="bg-white rounded-lg border border-gray-200 p-4 mb-4 shadow-sm">
        <h3 className="text-sm font-semibold text-gray-700 mb-1">Pre-Run Examples</h3>
        <p className="text-xs text-gray-400 mb-3">No API key needed. Click to view saved analysis results.</p>
        <div className="flex flex-wrap gap-2">
          {PRERUN_EXAMPLES.map((ex, i) => (
            <button key={i} onClick={() => loadPrerun(ex.name)} disabled={loading === 'prerun'}
              className="px-4 py-2 bg-gray-50 border border-gray-300 rounded-lg text-sm hover:bg-[#2171B5] hover:text-white hover:border-[#2171B5] transition-colors">
              {ex.label} &rarr;
            </button>
          ))}
        </div>
      </div>

      {/* Pre-run result display */}
      {prerunResult && !prerunResult.error && (
        <div className="bg-white rounded-lg border border-gray-200 p-5 mb-4 shadow-sm">
          <div className="text-xs text-gray-400 mb-2">Pre-run example result</div>
          <h3 className="text-sm font-semibold text-gray-700 mb-1">Query: {prerunResult.query}</h3>
          {prerunResult.plan_html && <div className="mt-3" dangerouslySetInnerHTML={{ __html: prerunResult.plan_html }} />}
          <div className="text-xs text-gray-500 my-2">{prerunResult.execution_status}</div>
          {prerunResult.results_html && <div className="mt-3" dangerouslySetInnerHTML={{ __html: prerunResult.results_html }} />}
        </div>
      )}

      {/* Model Configuration */}
      <div className="bg-white rounded-lg border border-gray-200 p-4 mb-4 shadow-sm">
        <h3 className="text-sm font-semibold text-gray-700 mb-3">Run Your Own Query</h3>

        {/* Mode toggle */}
        <div className="flex gap-2 mb-3">
          <button onClick={() => { setMode('free'); setProvider('Google Gemini'); setModel('gemini-2.5-flash'); }}
            className={`px-4 py-1.5 text-xs rounded-full border transition-colors ${mode === 'free' ? 'bg-[#238B45] text-white border-[#238B45]' : 'bg-white text-gray-600 border-gray-300 hover:bg-gray-100'}`}>
            Free Model (no API key)
          </button>
          <button onClick={() => setMode('custom')}
            className={`px-4 py-1.5 text-xs rounded-full border transition-colors ${mode === 'custom' ? 'bg-[#2171B5] text-white border-[#2171B5]' : 'bg-white text-gray-600 border-gray-300 hover:bg-gray-100'}`}>
            Custom API Key
          </button>
        </div>

        {mode === 'free' ? (
          <div className="flex items-center gap-3 mb-3">
            <span className="text-xs text-gray-500">Using: <strong>Google Gemini 2.5 Flash</strong> (free tier, no API key needed)</span>
            <button onClick={doInit} disabled={loading === 'init'}
              className="px-5 py-2 bg-[#238B45] text-white rounded-md text-sm font-medium hover:bg-[#1a6e35] disabled:opacity-50 transition-colors">
              {loading === 'init' ? 'Initializing...' : 'Initialize Free Model'}
            </button>
          </div>
        ) : (
          <div className="flex flex-wrap gap-3 items-end mb-3">
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Provider</label>
              <select value={provider} onChange={e => {
                setProvider(e.target.value);
                const info = providers[e.target.value];
                if (info) setModel(info.default);
              }}
                className="px-3 py-2 border border-gray-300 rounded-md text-sm w-44 bg-white focus:ring-1 focus:ring-[#2171B5] outline-none">
                {Object.keys(providers).map(p => <option key={p}>{p}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">Model Name</label>
              <input value={model} onChange={e => setModel(e.target.value)}
                placeholder={providerInfo ? `e.g., ${providerInfo.models.join(', ')}` : ''}
                className="px-3 py-2 border border-gray-300 rounded-md text-sm w-56 focus:ring-1 focus:ring-[#2171B5] outline-none" />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 mb-1">API Key</label>
              <input type="password" value={apiKey} onChange={e => setApiKey(e.target.value)}
                placeholder="Session only — not saved"
                className="px-3 py-2 border border-gray-300 rounded-md text-sm w-56 focus:ring-1 focus:ring-[#2171B5] outline-none" />
            </div>
            <button onClick={doInit} disabled={loading === 'init'}
              className="px-5 py-2 bg-[#2171B5] text-white rounded-md text-sm font-medium hover:bg-[#1a5a90] disabled:opacity-50 transition-colors">
              {loading === 'init' ? 'Initializing...' : 'Initialize'}
            </button>
          </div>
        )}
        {agentStatus && <p className="text-xs text-gray-600 mb-2">{agentStatus}</p>}

        {/* Example queries */}
        <div className="flex flex-wrap gap-2 mb-3">
          <span className="text-xs font-semibold text-gray-500 self-center">Try:</span>
          {examples.map((ex: any, i: number) => (
            <button key={i} onClick={() => setQuery(ex.query)}
              className="px-3 py-1 text-xs bg-gray-50 border border-gray-300 rounded-full hover:bg-[#2171B5] hover:text-white hover:border-[#2171B5] transition-colors">
              {ex.label}
            </button>
          ))}
        </div>

        <textarea value={query} onChange={e => setQuery(e.target.value)} rows={3}
          placeholder="e.g., How strong is the evidence that vemurafenib binds to BRAF?"
          className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:ring-1 focus:ring-[#2171B5] focus:border-[#2171B5] outline-none resize-y mb-2" />
        <div className="flex gap-2">
          <button onClick={doPlan} disabled={!!loading}
            className="px-5 py-2 bg-[#2171B5] text-white rounded-md text-sm font-medium hover:bg-[#1a5a90] disabled:opacity-50 transition-colors">
            {loading === 'plan' ? 'Generating...' : 'Generate Plan'}
          </button>
          <button onClick={doExecute} disabled={!!loading || !plan}
            className="px-5 py-2 bg-gray-600 text-white rounded-md text-sm font-medium hover:bg-gray-700 disabled:opacity-50 transition-colors">
            {loading === 'execute' ? 'Executing...' : 'Execute Plan'}
          </button>
        </div>
      </div>

      {/* Plan + Results */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {plan && (
          <div className="bg-white rounded-lg border border-gray-200 p-4 shadow-sm">
            <h3 className="text-sm font-semibold text-gray-700 mb-2">Plan Steps</h3>
            <ol className="space-y-2">
              {plan.steps.map((s: any) => (
                <li key={s.step_number} className="flex items-start gap-2 text-sm">
                  <span className="mt-0.5">{s.status === 'completed' ? '\u2705' : s.status === 'failed' ? '\u274C' : '\u23F3'}</span>
                  <div>
                    <div className="font-medium text-gray-700">{s.description}</div>
                    <div className="text-xs text-gray-400">{s.data_sources?.join(', ')}</div>
                  </div>
                </li>
              ))}
            </ol>
          </div>
        )}

        {results && (
          <div className="lg:col-span-2 bg-white rounded-lg border border-gray-200 p-4 shadow-sm">
            <h3 className="text-sm font-semibold text-gray-700 mb-2">Results</h3>
            <div className="mb-3 text-xs text-gray-500">
              {results.steps.filter((s: any) => s.status === 'completed').length}/{results.steps.length} steps completed
            </div>
            {results.steps.map((s: any) => (
              <div key={s.step_number} className="mb-3 p-3 bg-gray-50 rounded border border-gray-100">
                <div className="flex items-center gap-2 mb-1">
                  <span>{s.status === 'completed' ? '\u2705' : '\u274C'}</span>
                  <span className="text-sm font-medium">{s.description}</span>
                </div>
                {s.result_summary && <p className="text-xs text-gray-600 ml-6 break-words whitespace-pre-wrap">{s.result_summary}</p>}
                {s.error && <p className="text-xs text-red-500 ml-6">{s.error}</p>}
              </div>
            ))}
            {results.summary && (
              <div className="mt-4 p-4 bg-blue-50 rounded border border-blue-200">
                <h4 className="text-sm font-semibold text-gray-700 mb-2">Analysis Summary</h4>
                <div className="text-sm text-gray-700 leading-relaxed" dangerouslySetInnerHTML={{ __html: mdToHtml(results.summary) }} />
              </div>
            )}
            <div className="flex gap-2 mt-3">
              <button onClick={() => downloadMarkdown(query, plan, results)}
                className="px-3 py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded border border-gray-300 transition-colors">
                Download MD
              </button>
              <button onClick={() => downloadPDF(query, plan, results)}
                className="px-3 py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded border border-gray-300 transition-colors">
                Download PDF
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
